# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-GoodCodeExerciseSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'CodableFirebase'
  pod 'Alamofire'
  pod 'AlamofireImage'
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  # Pods for iOS-GoodCodeExerciseSample

  target 'iOS-GoodCodeExerciseSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
